### ISSUE TITLE
I cannot "npm start"

### ISSUE THREAD

**Issue by Nao000** [HVF/franchise#22]
hi. I want to try franchise with my pc. but I cannot "npm start".

Can somebody help me?

node.js ==> v8.5.0( using nodist )
npm     ==> v4.0.5( nwb is installed )
OS       ==> windows7 home 64bit

I installed franshise following  "Running Locally"

this is the error.
```

E:\github\franchise>npm start

> franchise@1.0.0 start E:\github\franchise
> nwb serve-react-app

Error running command: Cannot find module 'nwb-less' from 'E:\github\franchise'
Error: Cannot find module 'nwb-less' from 'E:\github\franchise'
    at Function.module.exports [as sync] (C:\Program Files (x86)\Nodist\bin\node
_modules\nwb\node_modules\resolve\lib\sync.js:40:15)
    at C:\Program Files (x86)\Nodist\bin\node_modules\nwb\lib\getPluginConfig.js
:71:50
    at Array.forEach (<anonymous>)
    at getPluginConfig (C:\Program Files (x86)\Nodist\bin\node_modules\nwb\lib\g
etPluginConfig.js:70:11)
    at webpackServer (C:\Program Files (x86)\Nodist\bin\node_modules\nwb\lib\web
packServer.js:91:54)
    at serve (C:\Program Files (x86)\Nodist\bin\node_modules\nwb\lib\appCommands
.js:161:31)
    at serveReact (C:\Program Files (x86)\Nodist\bin\node_modules\nwb\lib\comman
ds\serve-react-app.js:18:26)
    at cli (C:\Program Files (x86)\Nodist\bin\node_modules\nwb\lib\cli.js:263:5)

    at Object.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\nwb\li
b\bin\nwb.js:31:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\8.5.0\\node.exe" "C:\\Pro
gram Files (x86)\\Nodist\\npmv\\4.0.5\\bin\\npm-cli.js" "start"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! franchise@1.0.0 start: `nwb serve-react-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the franchise@1.0.0 start script 'nwb serve-react-app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the franchise package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nwb serve-react-app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs franchise
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls franchise
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     E:\github\franchise\npm-debug.log

E:\github\franchise>

```

**Comment by Marak** [comment]
Try running:

```bash
yarn install
yarn start
```

npm has become pretty unstable in its last few versions

**Comment by lovett** [comment]
The third-to-last line of the error message mentions that `node_modules` is missing. It should have been created when the project dependencies were installed via `yarn install` or `npm install`. If that step didn't happen then the rest of the application can't run, even if you already have `nwb` installed.

When `npm start` ran, it noticed that `nwb` was available in the global `node_modules` directory. That was good, but only until one of the other packages was needed (`nwb-less` in this case). Since it hadn't been installed, the start script failed

`yarn install` won't work unless you already have `yarn` installed. `npm install` should work because it is installed with Node.

If `npm install` fails because of a Windows-specific issue, you'd get a different error message.

**Comment by Nao000** [comment]
thank you, both of you.

I installed yarn, and I could try franchise.

I like this about graphical and right weight.

By the way, Can I translate Japanese this one ? (My English may be wrong.)

**Comment by bijection** [comment]
Glad this was resolved!
