### ISSUE TITLE
franchise-client SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by wallawaz** [HVF/franchise#27]
OSX 
node v6.11.3

I'm having issues getting the franchise client bridge to work locally.

I've tried the following:
```
Benjamin@MacBook-Pro:~/projects/franchise$ npx franchise-client
missing ) after argument list
```
```
Benjamin@MacBook-Pro:~/projects/franchise/node_modules/franchise-client$ ./server.js 
/Users/Benjamin/projects/franchise/node_modules/franchise-client/server.js:16
	ws.on('message', async message => {
	                 ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```
I've added all env variables required by `credentials.js`  to my env.
Any suggestions?
Thanks

**Comment by ian-patel** [comment]
+1

**Comment by bijection** [comment]
This is throwing an error because the version of node you're running doesn't support async functions. For now, you should install a version that does, eg node 8.

We're looking into relaxing this requirement.

**Comment by bijection** [comment]
The node version requirement should be slightly relaxed. Does npx franchise-client still throw that error?

**Comment by bijection** [comment]
Closing this for inactivity, but feel free to reply if it's still not working for you.
